// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZUgGOFFrvfv99qox4c3mMW8MnyMVl1-w',
    appId: '1:866298329276:web:a4259fb1f49431a2dfb8b9',
    messagingSenderId: '866298329276',
    projectId: 'signin-7fe4e',
    authDomain: 'signin-7fe4e.firebaseapp.com',
    storageBucket: 'signin-7fe4e.appspot.com',
    measurementId: 'G-BTJP17E198',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiEvf5Rd3_GH4TzCAIaP1XxNMkYXVzxG0',
    appId: '1:866298329276:android:5f73996174c0f1b2dfb8b9',
    messagingSenderId: '866298329276',
    projectId: 'signin-7fe4e',
    storageBucket: 'signin-7fe4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv6Aj7oM7LZ1KNQVJOd1_GtKsuhuUjy2k',
    appId: '1:866298329276:ios:ccdd72a342037aa8dfb8b9',
    messagingSenderId: '866298329276',
    projectId: 'signin-7fe4e',
    storageBucket: 'signin-7fe4e.appspot.com',
    iosBundleId: 'com.example.signinsignout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv6Aj7oM7LZ1KNQVJOd1_GtKsuhuUjy2k',
    appId: '1:866298329276:ios:ccdd72a342037aa8dfb8b9',
    messagingSenderId: '866298329276',
    projectId: 'signin-7fe4e',
    storageBucket: 'signin-7fe4e.appspot.com',
    iosBundleId: 'com.example.signinsignout',
  );
}
